---
- hosts: all
  # become: true
  vars:
    home_dir: "/home/vagrant"
    file_owner: vagrant

  tasks:

  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - resolvconf
      - build-essential
      - git 
      - libssl-dev 
      - man
      - openjdk-8-jdk
      - unzip
      - zip
      - maven
      - jq
    become: yes

  - name: Add configuration block in /etc/resolvconf/resolv.conf.d/head
    blockinfile:
      path: /etc/resolvconf/resolv.conf.d/head
      block: |
        nameserver 8.8.8.8
        nameserver 8.8.4.4
    become: yes

  - name: Restart resolvconf
    service:
      name: resolvconf
      state: restarted
    become: yes

  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    become: yes

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
    become: yes

  - name: Install docker and its dependecies
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    notify:
      - docker status
    become: yes

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      group: docker
    become: yes

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none
    become: yes

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0
    become: yes
    
  - name: download golang  
    get_url:
      url: "https://golang.org/dl/go1.15.10.linux-amd64.tar.gz"
      dest: "{{home_dir}}"
      mode: 0440
     
  - name: Remove old installation of Go
    file:
      path: /usr/local/go
      state: absent
    become: yes
 
  - name: Extract the Go tarball
    unarchive:
      src: "{{home_dir}}/go1.15.10.linux-amd64.tar.gz"
      dest: /usr/local
      copy: no
    become: yes
 
  - name: create go directories in home
    file:
      path: "{{item}}"
      state: directory
      owner: "{{file_owner}}"
      group: "{{file_owner}}"
      mode: 0775
    with_items:
    - "{{home_dir}}/go"
    - "{{home_dir}}/go/bin"
     
  - name: modify .bashrc
    blockinfile:
      dest: "{{home_dir}}/.bashrc"
      block: |
        export GOPATH=$HOME/go
        export GOBIN=$GOPATH/bin
        export PATH=$GOBIN:$PATH:/usr/local/go/bin
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        export MAVEN_HOME=/usr/share/maven/usr/share/maven
        export PATH=$PATH:$JAVA_HOME/bin:$MAVEN_HOME/bin
      marker: '# {mark} ANSIBLE MANAGED BLOCK - changes for golang'
      insertafter: EOF
      create: yes 
     
  - name: Remove the Go tarball
    file:
      path: "{{home_dir}}/go1.15.10.linux-amd64.tar.gz"
      state: absent
    become: yes

  - name: download docker-compose  
    get_url: 
      url : https://github.com/docker/compose/releases/download/1.28.6/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'
    become: yes

  - name: Change file ownership, group and permissions
    file:
      path: /usr/local/bin/docker-compose
      owner: vagrant
      group: vagrant
      mode: '0755'
    become: yes

  - name: Change file ownership, group and permissions
    file:
      path: /opt/gradle
      state: directory
      mode: '0755'
    become: yes

  - name: download Gradle and unarchive 
    unarchive:
      src: https://services.gradle.org/distributions/gradle-6.7-bin.zip
      dest: /opt/gradle
      remote_src: yes
    become: yes
     
  - name: modify .bashrc
    blockinfile:
      dest: "{{home_dir}}/.bashrc"
      block: |
        export GRADLE_HOME=/opt/gradle/gradle
        export PATH=${GRADLE_HOME}/bin:${PATH}
      marker: '# {mark} ANSIBLE MANAGED BLOCK - changes for Gradle'
      insertafter: EOF
      create: yes 
     
  - name: Download nvm script
    get_url:
      url: https://raw.githubusercontent.com/creationix/nvm/v0.35.3/install.sh 
      dest: /tmp/install.sh 
      mode: '0440'

  - name: Change file ownership, group and permissions
    file:
      path: /tmp/install.sh 
      owner: vagrant
      group: vagrant
      mode: '0755'

  - name: Install nvm
    shell: /tmp/install.sh 

  - name: Source nvm
    shell: . ~/.profile 

  - name: Install node and set version
    shell: >
      /bin/bash -c "source ~/.nvm/nvm.sh && nvm install v14.16.0 && nvm alias default v14.16.0"
      


  handlers:
    - name: docker status
      service: name=docker state=started
